# serviceaccount-with-secret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cms-admin
  namespace: cms
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-admin-secret
  namespace: cms
  annotations:
    kubernetes.io/service-account.name: cms-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
kind: RoleBinding
metadata:
  name: cms-admin-binding
  namespace: cms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #name: cluster-admin  #内置权限
  name: admin  #内置权限
subjects:
- kind: ServiceAccount
  name: cms-admin
  namespace: cms
