# serviceaccount-with-secret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cms-dev
  namespace: cms
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-dev-secret
  namespace: cms
  annotations:
    kubernetes.io/service-account.name: cms-dev
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cms
  name: cms-dev
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cms-dev-binding
  namespace: cms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cms-dev
subjects:
- kind: ServiceAccount
  name: cms-dev
  apiGroup: 
