# serviceaccount-with-secret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cms-view
  namespace: cms
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-view-secret
  namespace: cms
  annotations:
    kubernetes.io/service-account.name: cms-view
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cms-view-binding
  namespace: cms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view  #内置权限
subjects:
- kind: ServiceAccount
  name: cms-view
  namespace: cms
