#创建一个Pod类型的nfs-client
apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  namespace: cms
  labels:
    app: nfs-client
spec:
  containers:
  - name: nfs-client
    image: alpine-nfsclient
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["/run.sh && tail -f /dev/null"]
