#创建一个Pod类型的nfs-client
apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  namespace: cms
  labels:
    app: nfs-client
spec:
  containers:
  - name: nfs-client
    image: alpine-nfsclient
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["mount -o ro -t nfs nfs-server:/nfsshare/seacms/app /nfsshare && tail -f /dev/null"]
    volumeMounts:
    - mountPath: "/nfsshare"
      name: nfsshare
  volumes:
   - name: nfsshare
