apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: seacms
  name: seacms
  namespace: cms
spec:
  ports:
  - name: seacms
    protocol: TCP
    port: 2080
    targetPort: 80
  - name: mdb
    protocol: TCP
    port: 2006
    targetPort: 3306
  selector:
    app: seacms
  type: NodePort
