#创建一个Deployment类型的app(seacms-app-master)
kind: Deployment
metadata:
  name: seacms-app-master
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app-m: seacms-master
  template:
    metadata:
      labels:
        app-m: seacms-master
    spec:
      containers:
      - name: seacms-app-master
        image: seacms-app
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          requests:
            cpu: "5m"
            memory: "30Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/localhost/htdocs"
          name: seacmsapp-master
      volumes:
      - name: seacmsapp-master
        hostPath:
          path: "/seacms/app"
          type: DirectoryOrCreate
---
#创建一个Deployment类型的app(seacms-mdb-master)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seacms-mdb-master
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app-m: seacms-master
  template:
    metadata:
      labels:
        app-m: seacms-master
    spec:
      containers:
      - name: seacms-mdb-master
        image: seacms-mdb
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          requests:
            cpu: "15m"
            memory: "90Mi"
          limits:
            cpu: "100m"
            memory: "150Mi"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: seacmsmdb-master
      volumes:
      - name: seacmsmdb-master
        hostPath:
          path: /seacms/mdb
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: seacms
  namespace: cms
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80           #service对外端口
    targetPort: 80     #容器端口
    nodePort: 30081    #nodeport
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30306
  selector:
    app-m: seacms-master
  type: NodePort
