#创建namespace:cms
apiVersion: v1  #指定了 Kubernetes API 的版本为v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cms    #与命名空间名一致
  name: cms
---
#创建StorageClass
#在 k8s 1.20 之后，出于对性能和统一 apiserver 调用方式的初衷，k8s 移除了对 SelfLink 的支持，而默认上面指定的 provisioner 版本需要 SelfLink 功能，因此 PVC 无法进行自动制备。
#参考链接：https://juejin.cn/post/7329867093871116298
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  #WaitForFirstConsumer模式，将推迟绑定PV直到Pod实际需要它，这有助于确保Pod与正确的PV配对
---
#创建一个PV,挂载本地目录/seacms/app
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: seacms-app
  name: seacms-app
  #namespace: cms                 #PV是集群资源，不是命名空间资源
spec:
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #回收策略，保留，需要手动回收
  storageClassName: local-storage       #使用local-storage存储组策略
  #hostPath:         #local卷类型应该使用spec.local.path而不是hostPath
  local:
    path: /seacms/app  #本地存储路径，必须事先存在于节点上
  nodeAffinity:   #确保PV与特定节点关联
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master    #指定了节点亲和性以确保该PV仅能在名为k8s-master的节点上使用
---
#创建一个PVC(seacms-app)，绑定PV(seacms-app）
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seacms-app
  namespace: cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
  storageClassName: local-storage       #使用local-storage存储组策略
  selector:
    matchLabels:
      volume: seacms-app  #通过label绑定PV(seacms-app)
---
#创建一个PV挂载本地目录/seacms/mdb
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: seacms-mdb
  name: seacms-mdb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #回收策略，保留，需要手动回收
  storageClassName: local-storage
  local:
    path: /seacms/mdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master  #指定了节点亲和性以确保该PV仅能在名为k8s-master的节点上使用
---
#创建一个PVC(seacms-mdb)，绑定PV(seacms-mdb）
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seacms-mdb
  namespace: cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage       #使用local-storage存储组策略
  selector:
    matchLabels:
      volume: seacms-mdb  #通过label绑定PV(seacms-mdb)
---
#创建一个Deployment类型的app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seacms
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      task: web
      app: seacms
  template:
    metadata:
      labels:
        task: web
        app: seacms
    spec:
      containers:
      - name: seacms
        image: seacms
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/localhost/htdocs"
          name: seacmsapp
        - mountPath: "/var/lib/mysql"
          name: seacmsmdb
      volumes:
      - name: seacmsapp
        persistentVolumeClaim:
          claimName: seacms-app  #PVC名字
      - name: seacmsmdb
        persistentVolumeClaim:
          claimName: seacms-mdb  #PVC名字
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: seacms
  name: seacms
  namespace: cms
spec:
  ports:
  - port: 2080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  - port: 2006
    protocol: TCP
    targetPort: 3306
    nodePort: 33306
  selector:
    app: seacms
  type: NodePort
