#创建一个PV,挂载本地目录/seacms/app
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: seacms-app
  name: seacms-app
  #namespace: cms                 #PV是集群资源，不是命名空间资源
spec:
  capacity:
    storage: 30Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs.server.com
    path: /seacms/app
---
#创建一个PVC(seacms-app)，绑定PV(seacms-app）
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seacms-app
  namespace: cms
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Mi
  selector:
    matchLabels:
      volume: seacms-app  #通过label绑定PV(seacms-app)
---
#创建一个PV挂载本地目录/seacms/mdb
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: seacms-mdb
  name: seacms-mdb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.server.com
    path: /seacms/mdb
---
#创建一个PVC(seacms-mdb)，绑定PV(seacms-mdb）
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seacms-mdb
  namespace: cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: seacms-mdb  #通过label绑定PV(seacms-mdb)
---
#创建一个StatefulSet类型的app(seacms-app)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seacms-app
  namespace: cms
spec:
  serviceName: seacms-app  #Headless Service
  replicas: 1
  selector:
    matchLabels:
      app: seacms
  template:
    metadata:
      labels:
        app: seacms
    spec:
      containers:
      - name: seacms-app
        image: seacms-app
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/localhost/htdocs"
          name: seacmsapp
      volumes:
      - name: seacmsapp
        persistentVolumeClaim:
          claimName: seacms-app  #PVC名字
---
#创建一个Deployment类型的app(seacms-mdb)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seacms-mdb
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seacms
  template:
    metadata:
      labels:
        app: seacms
    spec:
      containers:
      - name: seacms-mdb
        image: seacms-mdb
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: seacmsmdb
      volumes:
      - name: seacmsmdb
        persistentVolumeClaim:
          claimName: seacms-mdb  #PVC名字
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: seacms
  name: seacms
  namespace: cms
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80           #service对外端口
    targetPort: 80     #容器端口
    nodePort: 30080    #nodeport
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30306
  selector:
    app: seacms
  type: NodePort
