apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: seacms-app
  namespace: cms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: seacms-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu #或memory
      container: seacms-app  #目标容器名称
      target:
        type: Utilization
        averageUtilization: 80
