#创建namespace: cms
apiVersion: v1  #指定了 Kubernetes API 的版本为v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cms    #与命名空间名一致
  name: cms
---
#创建一个StatefulSet类型的app
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seacms
  namespace: cms
spec:
  serviceName: seacms  #Headless Service
  replicas: 1
  selector:
    matchLabels:
      app: seacms
  template:
    metadata:
      labels:
        app: seacms
    spec:
      containers:
      - name: seacms-app
        image: seacms-app
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/localhost/htdocs"
          name: seacmsapp
      - name: seacms-mdb
        image: seacms-mdb
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          limits:
            cpu: "100m"
            memory: "150Mi"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: seacmsmdb
      volumes:
      - name: seacmsapp
        hostPath:
          path: "/seacms/app"
          type: DirectoryOrCreate
      - name: seacmsmdb
        hostPath:
          path: /seacms/mdb
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: seacms
  namespace: cms
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80           #service对外端口
    targetPort: 80     #容器端口
    nodePort: 30080    #nodeport
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30306
  selector:
    app: seacms
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: seacms-hpa
  namespace: cms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: seacms
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu #或memory
      container: seacms-app  #目标容器名称
      target:
        type: Utilization
        averageUtilization: 80
