apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: seacms-app
  namespace: cms
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: seacms-app
  targetCPUUtilizationPercentage: 80
