#创建一个StatefulSet类型的app(seacms-app)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seacms-app-slave
  namespace: cms
spec:
  serviceName: seacms-app-slave  #Headless Service
  replicas: 1
  selector:
    matchLabels:
      app-s: seacms-slave
  template:
    metadata:
      labels:
        app-s: seacms-slave
    spec:
      containers:
      - name: seacms-app-slave
        image: seacms-app-nfs
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          requests:
            cpu: "3m"
            memory: "30Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"
        ports:
        - containerPort: 80
          name: web-slave
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/localhost/htdocs"
          name: seacmsapp
      volumes:
      - name: seacmsapp
        nfs:
          server: nfs.server.com #NFS服务器IP
          path: /seacms/app    #NFS共享目录
          readOnly: true      #可选，默认可读写
---
#创建一个Deployment类型的app(seacms-mdb-slave)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seacms-mdb-slave
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app-s: seacms-slave
  template:
    metadata:
      labels:
        app-s: seacms-slave
    spec:
      containers:
      - name: seacms-mdb-slave
        image: seacms-mdb-nfs
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["/run.sh && tail -f /dev/null"]
        resources:
          requests:
            cpu: "15m"
            memory: "90Mi"
          limits:
            cpu: "100m"
            memory: "150Mi"
        ports:
        - containerPort: 3306
          name: mysql-slave
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: seacmsmdb
      volumes:
      - name: seacmsmdb
        nfs:
          server: nfs.server.com #NFS服务器IP
          path: /seacms/mdb    #NFS共享目录
          readOnly: true      #可选，默认可读写
---
apiVersion: v1
kind: Service
metadata:
  name: seacms-slave
  namespace: cms
spec:
  ports:
  - name: web-slave
    protocol: TCP
    port: 80           #service对外端口
    targetPort: 80     #容器端口
    nodePort: 30080    #nodeport
  - name: mysql-slave
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app-s: seacms-slave
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: seacms-app-slave
  namespace: cms
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: seacms-app-slave
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: seacms-mdb-slave
  namespace: cms
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seacms-mdb-slave
  targetCPUUtilizationPercentage: 90
